import { Question } from './types';

export const OFFICIAL_QUESTIONS: Question[] = [
  {
    id: 1,
    question_en: "What is the supreme law of the land?",
    question_es: "¿Cuál es la ley suprema de la nación?",
    answer_en: ["The Constitution"],
    answer_es: ["La Constitución"],
    distractors_es: ["La Declaración de Independencia", "La Carta de Derechos", "El Código Penal Federal"],
    explanation_es: "La Constitución es la ley fundamental que establece el gobierno de EE. UU. y protege los derechos de los ciudadanos. Todas las demás leyes están subordinadas a ella.",
    is_6520: true,
    category: "A: Principles of American Government",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/We_the_People_-_Preamble_to_the_United_States_Constitution.svg/1920px-We_the_People_-_Preamble_to_the_United_States_Constitution.svg.png"
  },
  {
    id: 2,
    question_en: "What does the Constitution do?",
    question_es: "¿Qué hace la Constitución?",
    answer_en: ["sets up the government", "defines the government", "protects basic rights of Americans"],
    answer_es: ["establece el gobierno"],
    distractors_es: ["Declara la guerra", "Paga las deudas del país", "Elige al Presidente directamente"],
    explanation_es: "La Constitución crea la estructura de los tres poderes del gobierno (Legislativo, Ejecutivo, Judicial), define sus funciones y limitaciones, y garantiza las libertades individuales.",
    is_6520: false,
    category: "A: Principles of American Government",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/US_Capitol_Building_at_night_2021.jpg/1920px-US_Capitol_Building_at_night_2021.jpg"
  },
  {
    id: 3,
    question_en: "The idea of self-government is in the first three words of the Constitution. What are these words?",
    question_es: "La idea del autogobierno está en las tres primeras palabras de la Constitución. ¿Cuáles son estas palabras?",
    answer_en: ["We the People"],
    answer_es: ["Nosotros el Pueblo"],
    distractors_es: ["Libertad y Justicia", "E Pluribus Unum", "En Dios Confiamos"],
    explanation_es: "'Nosotros el Pueblo' (We the People) son las palabras iniciales que declaran que el poder del gobierno proviene de los ciudadanos, no de un rey o dictador.",
    is_6520: false,
    category: "A: Principles of American Government",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/We_the_People_-_Preamble_to_the_United_States_Constitution.svg/1920px-We_the_People_-_Preamble_to_the_United_States_Constitution.svg.png"
  },
  {
    id: 4,
    question_en: "What is an amendment?",
    question_es: "¿Qué es una enmienda?",
    answer_en: ["a change (to the Constitution)", "an addition (to the Constitution)"],
    answer_es: ["un cambio (a la Constitución)"],
    distractors_es: ["Una ley aprobada por el Congreso", "Un veto del Presidente", "Una decisión de la Corte Suprema"],
    explanation_es: "Una enmienda es un proceso formal para modificar la Constitución. Permite que el documento se adapte a los cambios en la sociedad a lo largo del tiempo.",
    is_6520: false,
    category: "A: Principles of American Government",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/National_Archives_Building%2C_Washington_DC.jpg/1920px-National_Archives_Building%2C_Washington_DC.jpg"
  },
  {
    id: 5,
    question_en: "What do we call the first ten amendments to the Constitution?",
    question_es: "¿Con qué nombre se conocen las primeras diez enmiendas a la Constitución?",
    answer_en: ["The Bill of Rights"],
    answer_es: ["La Carta de Derechos"],
    distractors_es: ["Los Artículos de la Confederación", "El Preámbulo", "La Declaración de Emancipación"],
    explanation_es: "La Carta de Derechos (Bill of Rights) son las primeras 10 enmiendas, y su propósito principal es proteger libertades fundamentales como la libertad de expresión, religión y prensa.",
    is_6520: true,
    category: "A: Principles of American Government",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Bill_of_Rights_Pg1of1_AC.jpg/800px-Bill_of_Rights_Pg1of1_AC.jpg"
  },
  {
    id: 6,
    question_en: "What is one right or freedom from the First Amendment?",
    question_es: "¿Cuál es un derecho o libertad que la Primera Enmienda garantiza?",
    answer_en: ["speech", "religion", "assembly", "press", "petition the government"],
    answer_es: ["expresión"],
    distractors_es: ["El derecho a portar armas", "El derecho a un juicio rápido", "El derecho a votar"],
    explanation_es: "La Primera Enmienda es crucial para la democracia, ya que protege cinco libertades básicas: de expresión, de religión, de prensa, de reunión pacífica y de solicitar al gobierno que corrija errores.",
    is_6520: true,
    category: "A: Principles of American Government",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/First_Amendment_tablet_at_the_Newseum.jpg/1280px-First_Amendment_tablet_at_the_Newseum.jpg"
  },
  {
    id: 7,
    question_en: "How many amendments does the Constitution have?",
    question_es: "¿Cuántas enmiendas tiene la Constitución?",
    answer_en: ["twenty-seven (27)"],
    answer_es: ["veintisiete (27)"],
    distractors_es: ["Diez (10)", "Cincuenta (50)", "Cien (100)"],
    explanation_es: "La Constitución ha sido enmendada 27 veces desde su ratificación en 1788, lo que demuestra su capacidad para adaptarse a los cambios sociales y políticos a lo largo de la historia de la nación.",
    is_6520: false,
    category: "A: Principles of American Government",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/27th_Amendment_Pg1of1_AC.jpg/800px-27th_Amendment_Pg1of1_AC.jpg"
  },
  {
    id: 8,
    question_en: "What did the Declaration of Independence do?",
    question_es: "¿Qué hizo la Declaración de Independencia?",
    answer_en: ["announced our independence (from Great Britain)", "declared our independence (from Great Britain)", "said that the United States is free (from Great Britain)"],
    answer_es: ["anunció nuestra independencia (de Gran Bretaña)"],
    distractors_es: ["Estableció el gobierno", "Creó la Carta de Derechos", "Liberó a los esclavos"],
    explanation_es: "La Declaración de Independencia, adoptada el 4 de julio de 1776, fue un documento que proclamó formalmente que las trece colonias americanas se consideraban una nueva nación, independiente del Imperio Británico.",
    is_6520: false,
    category: "A: Principles of American Government",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Declaration_of_Independence_%281819%29%2C_by_John_Trumbull.jpg/1920px-Declaration_of_Independence_%281819%29%2C_by_John_Trumbull.jpg"
  },
  {
    id: 13,
    question_en: "Name one branch or part of the government.",
    question_es: "Nombre una rama o parte del gobierno.",
    answer_en: ["Congress", "legislative", "President", "executive", "the courts", "judicial"],
    answer_es: ["Congreso"],
    distractors_es: ["Los estados", "La policía", "El ejército"],
    explanation_es: "El gobierno de EE. UU. se divide en tres ramas para asegurar un equilibrio de poder: el Congreso (poder legislativo), el Presidente (poder ejecutivo) y los tribunales (poder judicial).",
    is_6520: true,
    category: "B: System of Government",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Branches_of_Government_3.svg/1280px-Branches_of_Government_3.svg.png"
  },
  {
    id: 16,
    question_en: "Who makes federal laws?",
    question_es: "¿Quién crea las leyes federales?",
    answer_en: ["Congress", "Senate and House (of Representatives)", "(U.S. or national) legislature"],
    answer_es: ["el Congreso"],
    distractors_es: ["El Presidente", "La Corte Suprema", "Los estados"],
    explanation_es: "El poder legislativo, compuesto por el Senado y la Cámara de Representantes, es el responsable de debatir, redactar y aprobar las leyes que se aplican a todo el país.",
    is_6520: false,
    category: "B: System of Government",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/United_States_Capitol_west_front_edit2.jpg/1280px-United_States_Capitol_west_front_edit2.jpg"
  },
  {
    id: 17,
    question_en: "What are the two parts of the U.S. Congress?",
    question_es: "¿Cuáles son las dos partes que integran el Congreso de los EE. UU.?",
    answer_en: ["the Senate and House (of Representatives)"],
    answer_es: ["el Senado y la Cámara (de Representantes)"],
    distractors_es: ["El gabinete y los tribunales", "El Presidente y el Vicepresidente", "Los partidos Demócrata y Republicano"],
    explanation_es: "El Congreso de los Estados Unidos es bicameral, lo que significa que está compuesto por dos cámaras: el Senado, que tiene igual representación para cada estado, y la Cámara de Representantes, cuya representación se basa en la población.",
    is_6520: false,
    category: "B: System of Government",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Seal_of_the_United_States_Congress.svg/1024px-Seal_of_the_United_States_Congress.svg.png"
  },
  {
    id: 20,
    question_en: "Who is one of your state’s U.S. Senators now?",
    question_es: "Nombre a uno de los senadores actuales del estado donde usted vive.",
    answer_en: ["Answers will vary. [District of Columbia residents and residents of U.S. territories should answer that D.C. (or the territory where the applicant lives) has no U.S. Senators.]"],
    answer_es: ["Las respuestas variarán"],
    distractors_es: ["El gobernador de mi estado", "El alcalde de mi ciudad", "El Presidente de la Cámara de Representantes"],
    explanation_es: "El Senado de los EE. UU. está compuesto por dos senadores de cada estado. Sus nombres varían según el estado y el momento de la elección. Es importante conocer a sus representantes.",
    is_6520: true,
    category: "B: System of Government",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Seal_of_the_United_States_Senate.svg/1024px-Seal_of_the_United_States_Senate.svg.png"
  },
  {
    id: 23,
    question_en: "Name your U.S. Representative.",
    question_es: "Dé el nombre de su representante a nivel nacional.",
    answer_en: ["Answers will vary."],
    answer_es: ["Las respuestas variarán"],
    distractors_es: ["El juez principal de la Corte Suprema", "El Vicepresidente de los Estados Unidos", "El Secretario de Estado"],
    explanation_es: "La Cámara de Representantes tiene miembros basados en la población de cada estado. Es crucial conocer a su representante local, ya que su nombre depende de su distrito electoral.",
    is_6520: true,
    category: "B: System of Government",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Seal_of_the_U.S._House_of_Representatives.svg/1024px-Seal_of_the_U.S._House_of_Representatives.svg.png"
  },
  {
    id: 26,
    question_en: "We elect a President for how many years?",
    question_es: "¿Por cuántos años elegimos a un Presidente?",
    answer_en: ["four (4)"],
    answer_es: ["cuatro (4)"],
    distractors_es: ["Dos (2)", "Seis (6)", "Ocho (8)"],
    explanation_es: "El mandato presidencial en los Estados Unidos es de cuatro años. Un presidente solo puede ser reelegido una vez, sirviendo un máximo de ocho años, según la 22ª Enmienda.",
    is_6520: false,
    category: "B: System of Government",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/The_White_House_at_night.jpg/1280px-The_White_House_at_night.jpg"
  },
  {
    id: 27,
    question_en: "In what month do we vote for President?",
    question_es: "¿En qué mes votamos por el Presidente?",
    answer_en: ["November"],
    answer_es: ["noviembre"],
    distractors_es: ["Enero", "Julio", "Diciembre"],
    explanation_es: "Las elecciones presidenciales en los Estados Unidos se llevan a cabo cada cuatro años el primer martes después del primer lunes de noviembre.",
    is_6520: true,
    category: "B: System of Government",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/US_Electoral_College_Map_2024.svg/1280px-US_Electoral_College_Map_2024.svg.png"
  },
  {
    id: 28,
    question_en: "What is the name of the President of the United States now?",
    question_es: "¿Cuál es el nombre del actual Presidente de los Estados Unidos?",
    answer_en: ["Donald Trump"],
    answer_es: ["Donald Trump"],
    distractors_es: ["Joe Biden", "Barack Obama", "Kamala Harris"],
    explanation_es: "Es importante saber el nombre del presidente actual, ya que es el jefe del poder ejecutivo y una figura central en el gobierno de EE. UU. (Información válida en 2025).",
    is_6520: true,
    category: "B: System of Government",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Donald_Trump_official_portrait.jpg/1024px-Donald_Trump_official_portrait.jpg"
  },
  {
    id: 33,
    question_en: "Who signs bills to become laws?",
    question_es: "¿Quién firma los proyectos de ley para convertirlos en ley?",
    answer_en: ["the President"],
    answer_es: ["el Presidente"],
    distractors_es: ["El Presidente de la Corte Suprema", "El Presidente del Senado", "El Secretario de Estado"],
    explanation_es: "Después de que un proyecto de ley es aprobado por ambas cámaras del Congreso, se envía al Presidente, quien tiene el poder de firmarlo para convertirlo en ley o vetarlo.",
    is_6520: false,
    category: "B: System of Government",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Seal_of_the_President_of_the_United_States.svg/1024px-Seal_of_the_President_of_the_United_States.svg.png"
  },
  {
    id: 37,
    question_en: "What does the judicial branch do?",
    question_es: "¿Qué hace la rama judicial?",
    answer_en: ["reviews laws", "explains laws", "resolves disputes (disagreements)", "decides if a law goes against the Constitution"],
    answer_es: ["revisa las leyes"],
    distractors_es: ["Crea las leyes", "Veta los proyectos de ley", "Comanda el ejército"],
    explanation_es: "La rama judicial, encabezada por la Corte Suprema, interpreta las leyes, determina si son constitucionales y resuelve disputas legales, asegurando que se apliquen de manera justa.",
    is_6520: false,
    category: "B: System of Government",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Supreme_Court_of_the_United_States_building.jpg/1280px-Supreme_Court_of_the_United_States_building.jpg"
  },
  {
    id: 38,
    question_en: "What is the highest court in the United States?",
    question_es: "¿Cuál es el tribunal más alto de los Estados Unidos?",
    answer_en: ["the Supreme Court"],
    answer_es: ["la Corte Suprema"],
    distractors_es: ["El Tribunal de Apelaciones", "El Tribunal Federal de Distrito", "El Senado"],
    explanation_es: "La Corte Suprema es el tribunal de última instancia en el sistema judicial federal. Sus decisiones son finales y establecen precedentes legales para todo el país.",
    is_6520: false,
    category: "B: System of Government",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Seal_of_the_United_States_Supreme_Court.svg/1024px-Seal_of_the_United_States_Supreme_Court.svg.png"
  },
  {
    id: 41,
    question_en: "Under our Constitution, some powers belong to the federal government. What is one power of the federal government?",
    question_es: "Bajo nuestra Constitución, algunos poderes pertenecen al gobierno federal. ¿Cuál es un poder del gobierno federal?",
    answer_en: ["to print money", "to declare war", "to create an army", "to make treaties"],
    answer_es: ["imprimir dinero"],
    distractors_es: ["Proveer educación", "Expedir licencias de conducir", "Aprobar la zonificación y el uso de la tierra"],
    explanation_es: "El gobierno federal tiene poderes específicos como imprimir moneda para mantener una economía unificada y declarar la guerra para proteger a la nación, que son responsabilidades a nivel nacional.",
    is_6520: false,
    category: "B: System of Government",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Seal_of_the_United_States_Department_of_the_Treasury.svg/1024px-Seal_of_the_United_States_Department_of_the_Treasury.svg.png"
  },
  {
    id: 44,
    question_en: "What is the capital of your state?",
    question_es: "¿Cuál es la capital de su estado?",
    answer_en: ["Answers will vary."],
    answer_es: ["Las respuestas variarán"],
    distractors_es: ["La ciudad más poblada de mi estado", "Washington, D.C.", "La ciudad de Nueva York"],
    explanation_es: "Cada estado de los EE. UU. tiene su propia capital, donde se encuentra la sede de su gobierno estatal. El nombre de la capital varía para cada estado.",
    is_6520: true,
    category: "C: Geography",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/State_capitals_of_the_United_States.svg/1920px-State_capitals_of_the_United_States.svg.png"
  },
  {
    id: 45,
    question_en: "What are the two major political parties in the United States?",
    question_es: "¿Cuáles son los dos principales partidos políticos de los Estados Unidos?",
    answer_en: ["Democratic and Republican"],
    answer_es: ["Demócrata y Republicano"],
    distractors_es: ["Libertario y Verde", "Independiente y Socialista", "Federalista y Whig"],
    explanation_es: "El sistema político de EE. UU. está dominado por dos partidos principales, el Demócrata y el Republicano, que representan diferentes ideologías y compiten por el control del gobierno.",
    is_6520: false,
    category: "B: System of Government",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Democratic_Donkey_and_Republican_Elephant.svg/1280px-Democratic_Donkey_and_Republican_Elephant.svg.png"
  },
  {
    id: 48,
    question_en: "There are four amendments to the Constitution about who can vote. Describe one of them.",
    question_es: "Existen cuatro enmiendas a la Constitución sobre quién puede votar. Describa una de ellas.",
    answer_en: ["Citizens eighteen (18) and older (can vote).", "You don’t have to pay (a poll tax) to vote.", "Any citizen can vote. (Women and men can vote.)", "A male citizen of any race (can vote)."],
    answer_es: ["Ciudadanos de dieciocho (18) años en adelante (pueden votar)."],
    distractors_es: ["Solo los propietarios de tierras pueden votar.", "Debes pasar un examen de alfabetización para votar.", "Solo las personas nacidas en EE. UU. pueden votar."],
    explanation_es: "A lo largo de la historia, varias enmiendas han ampliado el derecho al voto, prohibiendo la discriminación por raza (15ª), sexo (19ª), permitiendo el voto a los 18 años (26ª) y eliminando los impuestos electorales (24ª).",
    is_6520: false,
    category: "C: Rights and Responsibilities",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Vote_font_awesome.svg/1024px-Vote_font_awesome.svg.png"
  },
  {
    id: 52,
    question_en: "What is one promise you make when you become a United States citizen?",
    question_es: "¿Cuál es una promesa que usted hace cuando se convierte en ciudadano de los Estados Unidos?",
    answer_en: ["give up loyalty to other countries", "defend the Constitution and laws of the United States", "obey the laws of the United States", "serve in the U.S. military (if needed)", "serve (do important work for) the nation (if needed)", "be loyal to the United States"],
    answer_es: ["renunciar a la lealtad a otros países"],
    distractors_es: ["Votar en todas las elecciones", "Donar a un partido político", "Hablar inglés fluidamente"],
    explanation_es: "El Juramento de Lealtad es un compromiso solemne que incluye defender la Constitución, obedecer las leyes y ser leal a los Estados Unidos, dejando de lado lealtades a otras naciones.",
    is_6520: false,
    category: "C: Rights and Responsibilities",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Naturalization_ceremony_at_the_National_Archives.jpg/1280px-Naturalization_ceremony_at_the_National_Archives.jpg"
  },
  {
    id: 58,
    question_en: "What is one reason colonists came to America?",
    question_es: "¿Cuál es una razón por la que los colonos vinieron a América?",
    answer_en: ["freedom", "political liberty", "religious freedom", "economic opportunity", "practice their religion", "escape persecution"],
    answer_es: ["libertad"],
    distractors_es: ["Para unirse al imperio británico", "Para explorar los ríos", "Para luchar en la guerra franco-india"],
    explanation_es: "Los colonos llegaron a América por diversas razones, pero muchas estaban relacionadas con la búsqueda de libertades que no tenían en Europa, como la libertad religiosa y la oportunidad económica.",
    is_6520: false,
    category: "D: American History",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/The_Mayflower_Compact_1620_cph.3g07155.jpg/1280px-The_Mayflower_Compact_1620_cph.3g07155.jpg"
  },
  {
    id: 59,
    question_en: "Who lived in America before the Europeans arrived?",
    question_es: "¿Quiénes vivían en América antes de la llegada de los europeos?",
    answer_en: ["American Indians", "Native Americans"],
    answer_es: ["Indios Americanos"],
    distractors_es: ["Los vikingos", "Los africanos", "Los asiáticos"],
    explanation_es: "Antes de la colonización europea, el continente americano estaba habitado por una vasta y diversa población de pueblos indígenas, a menudo llamados Indios Americanos o Nativos Americanos.",
    is_6520: false,
    category: "D: American History",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/The_North_American_Indian_-_Plate_2_-_Prayer_to_the_Mystery.jpg/800px-The_North_American_Indian_-_Plate_2_-_Prayer_to_the_Mystery.jpg"
  },
  {
    id: 61,
    question_en: "Why did the colonists fight the British?",
    question_es: "¿Por qué lucharon los colonos contra los británicos?",
    answer_en: ["because of high taxes (taxation without representation)", "because the British army stayed in their houses (boarding, quartering)", "because they didn’t have self-government"],
    answer_es: ["debido a los altos impuestos (impuestos sin representación)"],
    distractors_es: ["Porque querían un rey propio", "Porque el rey prohibió el té", "Porque querían unirse a Francia"],
    explanation_es: "La lucha se originó porque los colonos creían que se les estaban negando sus derechos como británicos, especialmente al serles impuestos tributos sin tener representación en el Parlamento británico.",
    is_6520: false,
    category: "D: American History",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Boston_Tea_Party_Currier_colored.jpg/1280px-Boston_Tea_Party_Currier_colored.jpg"
  },
  {
    id: 62,
    question_en: "Who wrote the Declaration of Independence?",
    question_es: "¿Quién escribió la Declaración de Independencia?",
    answer_en: ["(Thomas) Jefferson"],
    answer_es: ["(Thomas) Jefferson"],
    distractors_es: ["(George) Washington", "(Benjamin) Franklin", "(John) Adams"],
    explanation_es: "Thomas Jefferson fue el autor principal de la Declaración de Independencia, un documento que articulaba las razones por las que las colonias buscaban separarse de Gran Bretaña.",
    is_6520: true,
    category: "D: American History",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Official_Presidential_portrait_of_Thomas_Jefferson_%28by_Rembrandt_Peale%2C_1800%29.jpg/800px-Official_Presidential_portrait_of_Thomas_Jefferson_%28by_Rembrandt_Peale%2C_1800%29.jpg"
  },
  {
    id: 63,
    question_en: "When was the Declaration of Independence adopted?",
    question_es: "¿Cuándo fue adoptada la Declaración de Independencia?",
    answer_en: ["July 4, 1776"],
    answer_es: ["El 4 de julio de 1776"],
    distractors_es: ["El 14 de junio de 1775", "El 17 de septiembre de 1787", "El 25 de diciembre de 1776"],
    explanation_es: "El 4 de julio de 1776 es la fecha en que el Congreso Continental adoptó formalmente la Declaración de Independencia, marcando el nacimiento de los Estados Unidos como una nación independiente.",
    is_6520: true,
    category: "D: American History",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Declaration_of_Independence_%281819%29%2C_by_John_Trumbull.jpg/1920px-Declaration_of_Independence_%281819%29%2C_by_John_Trumbull.jpg"
  },
  {
    id: 65,
    question_en: "What happened at the Constitutional Convention?",
    question_es: "¿Qué ocurrió en la Convención Constitucional?",
    answer_en: ["The Constitution was written.", "The Founding Fathers wrote the Constitution."],
    answer_es: ["Se redactó la Constitución."],
    distractors_es: ["Se firmó la Declaración de Independencia.", "George Washington fue elegido presidente.", "Se declaró la guerra contra Gran Bretaña."],
    explanation_es: "La Convención Constitucional se reunió en Filadelfia en 1787 con el objetivo de revisar los Artículos de la Confederación, pero terminó por redactar un documento completamente nuevo: la Constitución de los Estados Unidos.",
    is_6520: false,
    category: "D: American History",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Scene_at_the_Signing_of_the_Constitution_of_the_United_States.jpg/1280px-Scene_at_the_Signing_of_the_Constitution_of_the_United_States.jpg"
  },
  {
    id: 66,
    question_en: "When was the Constitution written?",
    question_es: "¿Cuándo fue redactada la Constitución?",
    answer_en: ["1787"],
    answer_es: ["1787"],
    distractors_es: ["1776", "1783", "1791"],
    explanation_es: "La Constitución fue redactada durante la Convención Constitucional en Filadelfia en el verano de 1787, y luego fue ratificada por los estados.",
    is_6520: true,
    category: "D: American History",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/National_Archives_Building%2C_Washington_DC.jpg/1920px-National_Archives_Building%2C_Washington_DC.jpg"
  },
  {
    id: 69,
    question_en: "Who is the “Father of Our Country”?",
    question_es: "¿Quién es el “Padre de Nuestra Patria”?",
    answer_en: ["(George) Washington"],
    answer_es: ["(George) Washington"],
    distractors_es: ["(Thomas) Jefferson", "(Abraham) Lincoln", "(Benjamin) Franklin"],
    explanation_es: "George Washington es conocido como el 'Padre de Nuestra Patria' por su liderazgo como comandante del Ejército Continental durante la Guerra de Independencia y por ser el primer presidente de los Estados Unidos.",
    is_6520: false,
    category: "D: American History",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Gilbert_Stuart_Williamstown_Portrait_of_George_Washington.jpg/800px-Gilbert_Stuart_Williamstown_Portrait_of_George_Washington.jpg"
  },
  {
    id: 70,
    question_en: "Who was the first President?",
    question_es: "¿Quién fue el primer Presidente?",
    answer_en: ["(George) Washington"],
    answer_es: ["(George) Washington"],
    distractors_es: ["(John) Adams", "(Thomas) Jefferson", "(James) Madison"],
    explanation_es: "Después de liderar el país hacia la victoria en la Guerra de Independencia, George Washington fue elegido por unanimidad como el primer Presidente de los Estados Unidos, sirviendo de 1789 a 1797.",
    is_6520: true,
    category: "D: American History",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Gilbert_Stuart_Williamstown_Portrait_of_George_Washington.jpg/800px-Gilbert_Stuart_Williamstown_Portrait_of_George_Washington.jpg"
  },
  {
    id: 71,
    question_en: "What territory did the United States buy from France in 1803?",
    question_es: "¿Qué territorio compró los Estados Unidos a Francia en 1803?",
    answer_en: ["the Louisiana Territory", "Louisiana"],
    answer_es: ["el territorio de Luisiana"],
    distractors_es: ["Florida", "Alaska", "Texas"],
    explanation_es: "La Compra de Luisiana fue una adquisición masiva de tierras que casi duplicó el tamaño de los Estados Unidos. Fue negociada por el presidente Thomas Jefferson.",
    is_6520: false,
    category: "D: American History",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Louisiana_Purchase.jpg/1280px-Louisiana_Purchase.jpg"
  },
  {
    id: 73,
    question_en: "Name one war fought by the United States in the 1800s.",
    question_es: "Nombre una guerra en la que peleó los Estados Unidos durante los años 1800.",
    answer_en: ["War of 1812", "Mexican-American War", "Civil War", "Spanish-American War"],
    answer_es: ["la Guerra Civil"],
    distractors_es: ["La Guerra de Independencia", "La Primera Guerra Mundial", "La Guerra de Vietnam"],
    explanation_es: "El siglo XIX fue un período de expansión y conflicto para los EE. UU., incluyendo la Guerra Civil (1861-1865), que fue el conflicto más mortífero en la historia del país y se luchó por la esclavitud y los derechos de los estados.",
    is_6520: false,
    category: "D: American History",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Battle_of_Gettysburg_by_Currier_and_Ives.jpg/1280px-Battle_of_Gettysburg_by_Currier_and_Ives.jpg"
  },
  {
    id: 74,
    question_en: "Name the U.S. war between the North and the South.",
    question_es: "Nombre la guerra de los EE. UU. entre el Norte y el Sur.",
    answer_en: ["the Civil War", "the War between the States"],
    answer_es: ["la Guerra Civil"],
    distractors_es: ["La Guerra de 1812", "La Guerra de Secesión", "La Revolución Americana"],
    explanation_es: "La Guerra Civil (1861-1865) fue un conflicto entre la Unión (los estados del Norte) y la Confederación (los estados del Sur que se separaron) sobre temas de esclavitud y soberanía estatal.",
    is_6520: false,
    category: "D: American History",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/The_Last_Meeting_of_Lee_and_Jackson.jpg/1280px-The_Last_Meeting_of_Lee_and_Jackson.jpg"
  },
  {
    id: 75,
    question_en: "Name one problem that led to the Civil War.",
    question_es: "Mencione un problema que condujo a la Guerra Civil.",
    answer_en: ["slavery", "economic reasons", "states' rights"],
    answer_es: ["esclavitud"],
    distractors_es: ["Impuestos al té", "Expansión hacia el oeste", "Diferencias religiosas"],
    explanation_es: "Aunque hubo múltiples factores, la esclavitud fue la causa central de la Guerra Civil. Las profundas divisiones económicas y morales sobre la institución de la esclavitud llevaron a la secesión y al conflicto.",
    is_6520: false,
    category: "D: American History",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Civil_War_contrabands_-_NARA_-_524750.jpg/1280px-Civil_War_contrabands_-_NARA_-_524750.jpg"
  },
  {
    id: 76,
    question_en: "What was one important thing that Abraham Lincoln did?",
    question_es: "¿Qué fue una cosa importante que hizo Abraham Lincoln?",
    answer_en: ["freed the slaves (Emancipation Proclamation)", "saved (or preserved) the Union", "led the United States during the Civil War"],
    answer_es: ["liberó a los esclavos (Proclamación de la Emancipación)"],
    distractors_es: ["Escribió la Constitución", "Compró el territorio de Luisiana", "Derrotó a los británicos en la Independencia"],
    explanation_es: "Abraham Lincoln, el 16º presidente, lideró el país durante la Guerra Civil. Su Proclamación de Emancipación en 1863 fue un paso crucial hacia la abolición de la esclavitud y cambió el curso de la guerra.",
    is_6520: true,
    category: "D: American History",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Abraham_Lincoln_O-77_matte_collodion_print.jpg/800px-Abraham_Lincoln_O-77_matte_collodion_print.jpg"
  },
  {
    id: 78,
    question_en: "What did Susan B. Anthony do?",
    question_es: "¿Qué hizo Susan B. Anthony?",
    answer_en: ["fought for women's rights", "fought for civil rights"],
    answer_es: ["luchó por los derechos de la mujer"],
    distractors_es: ["Fue la primera mujer en el Senado", "Escribió la Declaración de Independencia", "Luchó en la Guerra Civil"],
    explanation_es: "Susan B. Anthony fue una líder pionera en el movimiento por el sufragio femenino en los Estados Unidos. Dedicó su vida a luchar por el derecho de las mujeres a votar.",
    is_6520: false,
    category: "D: American History",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Susan_B_Anthony_c1855.jpg/800px-Susan_B_Anthony_c1855.jpg"
  },
  {
    id: 84,
    question_en: "What movement tried to end racial discrimination?",
    question_es: "¿Qué movimiento trató de poner fin a la discriminación racial?",
    answer_en: ["civil rights (movement)"],
    answer_es: ["el movimiento por los derechos civiles"],
    distractors_es: ["El movimiento de prohibición", "El movimiento sufragista", "El movimiento obrero"],
    explanation_es: "El movimiento por los derechos civiles, que alcanzó su apogeo en las décadas de 1950 y 1960, utilizó la resistencia no violenta y la desobediencia civil para luchar contra la segregación y la discriminación racial institucionalizada.",
    is_6520: false,
    category: "D: American History",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Official_program_for_the_March_on_Washington.jpg/800px-Official_program_for_the_March_on_Washington.jpg"
  },
  {
    id: 85,
    question_en: "What did Martin Luther King, Jr. do?",
    question_es: "¿Qué hizo Martin Luther King, Jr.?",
    answer_en: ["fought for civil rights", "worked for equality for all Americans"],
    answer_es: ["luchó por los derechos civiles"],
    distractors_es: ["Se postuló para presidente", "Fue un general en la Segunda Guerra Mundial", "Inventó la bombilla"],
    explanation_es: "Martin Luther King, Jr. fue la figura más prominente del movimiento por los derechos civiles, conocido por su defensa de la protesta no violenta y su famoso discurso 'Tengo un sueño'.",
    is_6520: true,
    category: "D: American History",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Martin_Luther_King%2C_Jr..jpg/800px-Martin_Luther_King%2C_Jr..jpg"
  },
  {
    id: 87,
    question_en: "Name one American Indian tribe in the United States.",
    question_es: "Mencione una tribu de indios americanos en los Estados Unidos.",
    answer_en: ["Cherokee", "Navajo", "Sioux", "Chippewa", "Choctaw", "Pueblo", "Apache", "Iroquois", "Creek", "Blackfeet", "Seminole", "Cheyenne", "Arawak", "Shawnee", "Mohegan", "Huron", "Oneida", "Lakota", "Crow", "Teton", "Hopi", "Inuit"],
    answer_es: ["Cherokee"],
    distractors_es: ["Azteca", "Inca", "Maya"],
    explanation_es: "Los Estados Unidos es hogar de numerosas tribus de Nativos Americanos reconocidas federalmente. Mencionar cualquiera de ellas demuestra conocimiento de la historia y diversidad del país.",
    is_6520: false,
    category: "D: American History",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Geronimo-1887.jpg/800px-Geronimo-1887.jpg"
  },
  {
    id: 88,
    question_en: "Name one of the two longest rivers in the United States.",
    question_es: "Mencione uno de los dos ríos más largos en los Estados Unidos.",
    answer_en: ["Missouri (River)", "Mississippi (River)"],
    answer_es: ["el río Missouri"],
    distractors_es: ["El río Colorado", "El río Ohio", "El río Hudson"],
    explanation_es: "El sistema fluvial Missouri-Mississippi es el más grande de América del Norte. El Missouri es técnicamente el más largo, pero a menudo se consideran juntos por su inmensa importancia geográfica y económica.",
    is_6520: false,
    category: "E: Geography",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Missouri_River_course_map.png/1024px-Missouri_River_course_map.png"
  },
  {
    id: 94,
    question_en: "What is the capital of the United States?",
    question_es: "¿Cuál es la capital de los Estados Unidos?",
    answer_en: ["Washington, D.C."],
    answer_es: ["Washington, D.C."],
    distractors_es: ["Nueva York", "Filadelfia", "Boston"],
    explanation_es: "Washington, D.C. (Distrito de Columbia) es la capital nacional, establecida por la Constitución para servir como sede del gobierno federal, y no forma parte de ningún estado.",
    is_6520: true,
    category: "E: Geography",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Washington_Monument_and_Reflecting_Pool.jpg/1280px-Washington_Monument_and_Reflecting_Pool.jpg"
  },
  {
    id: 95,
    question_en: "Where is the Statue of Liberty?",
    question_es: "¿Dónde está la Estatua de la Libertad?",
    answer_en: ["New York (Harbor)", "Liberty Island"],
    answer_es: ["(el puerto de) Nueva York"],
    distractors_es: ["Washington, D.C.", "San Francisco", "Boston"],
    explanation_es: "La Estatua de la Libertad, un regalo de Francia, se encuentra en Liberty Island, en el puerto de Nueva York, y ha sido un símbolo de libertad y bienvenida para los inmigrantes durante más de un siglo.",
    is_6520: true,
    category: "E: Symbols and Holidays",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Statue_of_Liberty_7.jpg/1024px-Statue_of_Liberty_7.jpg"
  },
  {
    id: 96,
    question_en: "Why does the flag have 13 stripes?",
    question_es: "¿Por qué hay 13 franjas en la bandera?",
    answer_en: ["because there were 13 original colonies", "because the stripes represent the original colonies"],
    answer_es: ["porque representan las 13 colonias originales"],
    distractors_es: ["Porque representa las primeras 13 enmiendas", "Porque 13 es un número de la suerte", "Porque representa los primeros 13 estados"],
    explanation_es: "Las 13 franjas horizontales, rojas y blancas, de la bandera estadounidense simbolizan las trece colonias británicas originales que se rebelaron contra la Corona y se convirtieron en los primeros estados de la Unión.",
    is_6520: false,
    category: "E: Symbols and Holidays",
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/1280px-Flag_of_the_United_States.svg.png"
  },
  {
    id: 97,
    question_en: "Why does the flag have 50 stars?",
    question_es: "¿Por qué hay 50 estrellas en la bandera?",
    answer_en: ["because there is one star for each state", "because each star represents a state", "because there are 50 states"],
    answer_es: ["porque hay una estrella por cada estado"],
    distractors_es: ["Porque hay 50 colonias", "Porque hay 50 enmiendas", "Porque representa los 50 firmantes de la Declaración"],
    explanation_es: "La bandera tiene 50 estrellas en el cantón azul, cada una representando a uno de los 50 estados que componen los Estados Unidos en la actualidad. El diseño ha cambiado a medida que se han añadido nuevos estados.",
    is_6520: false,
    category: "E: Symbols and Holidays",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/US_flag_50_stars.svg/1280px-US_flag_50_stars.svg.png"
  },
  {
    id: 98,
    question_en: "What is the name of the national anthem?",
    question_es: "¿Cómo se llama el himno nacional?",
    answer_en: ["The Star-Spangled Banner"],
    answer_es: ["The Star-Spangled Banner"],
    distractors_es: ["America the Beautiful", "God Bless America", "My Country, 'Tis of Thee"],
    explanation_es: "El himno nacional, 'The Star-Spangled Banner', fue escrito por Francis Scott Key durante la Guerra de 1812, inspirado por la visión de la bandera estadounidense ondeando sobre Fort McHenry después de un bombardeo.",
    is_6520: false,
    category: "E: Symbols and Holidays",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Star_Spangled_Banner_Flag.jpg/1280px-Star_Spangled_Banner_Flag.jpg"
  },
  {
    id: 99,
    question_en: "When do we celebrate Independence Day?",
    question_es: "¿Cuándo celebramos el Día de la Independencia?",
    answer_en: ["July 4"],
    answer_es: ["El 4 de julio"],
    distractors_es: ["El primer lunes de septiembre (Día del Trabajo)", "El último lunes de mayo (Día de los Caídos)", "El 11 de noviembre (Día de los Veteranos)"],
    explanation_es: "El 4 de julio se celebra como el Día de la Independencia porque en esa fecha, en 1776, se adoptó la Declaración de Independencia, el documento que proclamó la separación de las colonias de Gran Bretaña.",
    is_6520: true,
    category: "E: Symbols and Holidays",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Fireworks_in_New_York_City_for_Independence_Day_2009.jpg/1920px-Fireworks_in_New_York_City_for_Independence_Day_2009.jpg"
  },
  {
    id: 100,
    question_en: "Name two national U.S. holidays.",
    question_es: "Mencione dos días feriados nacionales de los Estados Unidos.",
    answer_en: ["New Year’s Day", "Martin Luther King, Jr. Day", "Presidents' Day", "Memorial Day", "Independence Day", "Labor Day", "Columbus Day", "Veterans Day", "Thanksgiving", "Christmas"],
    answer_es: ["Día de la Independencia", "Navidad"],
    distractors_es: ["Día de San Valentín", "Halloween", "Día de San Patricio"],
    explanation_es: "Los Estados Unidos reconoce varios días feriados federales que conmemoran eventos históricos importantes o figuras clave, como el Día de la Independencia, que celebra el nacimiento de la nación.",
    is_6520: false,
    category: "E: Symbols and Holidays",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Arlington_National_Cemetery_during_Memorial_Day_2015.jpg/1280px-Arlington_National_Cemetery_during_Memorial_Day_2015.jpg"
  }
];